### ISSUE TITLE
Exposure of API Key

### ISSUE THREAD

**Issue by Nixoff** [mgechev/gemini-angular-drawing-demo#1]
Hi Minko Gechev,

Hope you're doing well. I noticed that the API key is visible in your repository. Just wanted to give you a heads-up to prevent any security issues.

Here's the specific file where I observed the exposure: [Link to the File](https://github.com/mgechev/gemini-angular-drawing-demo/blob/main/src/app/generative.service.ts)

Recommended Action:

I suggest regenerating the API key.
Thanks for your attention!

Best,
Gabriel T.

**Comment by mgechev** [comment]
Yes, this is intentional to enable people to try the app at the deploy URL. Thanks for the heads up!
